name: CI-3p-postgresql
run-name: '${{ github.event.workflow_run && github.event.workflow_run.head_branch || github.ref_name }} ${{ github.workflow }} ${{ github.event.workflow_run && github.event.workflow_run.head_sha || github.sha }}'

on:
  workflow_dispatch:
    inputs:
      testtree:
        description: 'proxysql_3p_testing treeish/branch/tag/hash'
        default: main
        type: string
  workflow_run:
    workflows: [ CI-trigger ]
    types: [ completed ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run && github.event.workflow_run.head_branch || github.ref_name }}
  cancel-in-progress: true

jobs:
  run-pgsql:
    if: |
      (github.event.workflow_run && github.event.workflow_run.conclusion == 'success' || ! github.event.workflow_run) &&
      ! startsWith((github.event.workflow_run && github.event.workflow_run.head_branch || github.ref_name), 'v2.')
    uses: sysown/proxysql/.github/workflows/ci-3p-postgresql.yml@GH-Actions
    secrets: inherit
    with:
      trigger: ${{ toJson(github) }}
      infradb: ${{ vars.MATRIX_3P_POSTGRESQL_infradb_pgsql }}
      connector: ${{ vars.MATRIX_3P_POSTGRESQL_connector_pgsql }}
