name: CI-trigger
run-name: '${{ github.ref_name }} ${{ github.workflow }} ${{ github.sha }}'

on:
  pull_request:
    paths-ignore:
    - '.github/**'
    - '**.md' 
  push:
    branches:
    - 'v[0-9].[0-9x]+.?[0-9xy]?[0-9]?'
    paths-ignore:
    - '.github/**'
    - '**.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  run:
    uses: sysown/proxysql/.github/workflows/ci-trigger.yml@GH-Actions
    secrets: inherit
