name: CI-trigger

on:
  workflow_dispatch:
  workflow_call:

jobs:
  trigger:
    runs-on: ubuntu-22.04

    steps:
    - name: Trigger workflow_run[in_progress]
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set +e
        set -x

        echo "Get run id: '${{ github.ref_name }} ${{ github.workflow }} ${{ github.sha }}'"
        sleep 5
        RUNID=$(gh -R ${{ github.repository }} run list -w CI-builds -s in_progress | grep '${{ github.ref_name }} CI-builds ${{ github.sha }}' | grep -Po '(?<=workflow_run)\s+\d+')
        while [[ -z ${RUNID} ]]; do
          sleep 5
          RUNID=$(gh -R ${{ github.repository }} run list -w CI-builds -s in_progress | grep '${{ github.ref_name }} CI-builds ${{ github.sha }}' | grep -Po '(?<=workflow_run)\s+\d+')
        done
        echo "Run id: '${RUNID}' : '${{ github.ref_name }} ${{ github.workflow }} ${{ github.sha }}'"
        
        echo "Trigger workflow_run[in_progress]: '${{ github.ref_name }} ${{ github.workflow }} ${{ github.sha }}'"
        sleep 5
        # this blocks until the run is finished
        gh -R ${{ github.repository }} run watch -i 30 ${RUNID} >/dev/null
        sleep 5

    - name: Trigger workflow_run[completed]
      run: |
        echo "Triggered workflow_run[completed]: '${{ github.ref_name }} ${{ github.workflow }} ${{ github.sha }}'"
        
